#!/bin/bash
# Wrapper for any script that runs in ghidra (not using the ghidra_bridge)
/container/ghidra/support/analyzeHeadless /container/ghidra ghidra_project -import input/input.out -scriptPath /container/scripts -postscript "$@"
